directories:
  output: release
  buildResources: build
appId: com.example.myapp
productName: Casper
compression: maximum
win:
  target: portable
  icon: favicon.png
linux:
  category: Network
  icon: favicon.png
mac:
  category: Network
  icon: favicon.png
files:
  - filter:
      - index.js
      - favicon.png
extraFiles:
  - from: ./../../frontend/angular/dist/casper
    to: frontend/angular/dist/casper
electronVersion: 29.1.1
